export const CarouselData = [
    {
      image:
      "https://drive.google.com/uc?export=view&id=1mORBH9Nb_iHyf60tcaskpjKAgjn0_lZI",
    },
    {
      image:
      "https://drive.google.com/uc?export=view&id=1feuGmodqQPoFVUl0Hx67xN8i7yBw-N3q",
    },
    {
      image:
      "https://drive.google.com/uc?export=view&id=1-rkFlvOyz04XDqWCoJbtLz-iNo1vgg2q",
    },
    {
      image:
      "https://drive.google.com/uc?export=view&id=1ujpHJNoCUvi_qkAGSkSa-YiJ39WPeuZ2",
    },
    {
      image:
      "https://drive.google.com/uc?export=view&id=12AVrk-Wu0f1mbUYftNppLKZSXm1nGnGn",
    },
  ];