export const CarouselData = [
    {
      image:
        "./Assets/images/hero.jpg",
    },
    {
      image:
      "./Assets/images/hero2.jpg",
    },
    {
      image:
      "./Assets/images/hero3.jpg",
    },
    {
      image:
      "./Assets/images/hero4.jpg",
    },
    {
      image:
      "./Assets/images/hero5.jpg",
    },
  ];